[package]
name = "noahrepublic/loader2"
description = "A module loader without caching but direct string requiring similar to Quenty's loader. https://github.com/noahrepublic/RbxModules "
version = "0.2.2"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

