[package]
name = "noahrepublic/servicebag"
description = "Editted version of Quenty's ServiceBag https://github.com/noahrepublic/RbxModules "
version = "0.1.0"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Trove = "sleitnick/trove@1.0.1"
Signal = "sleitnick/signal@1.5.0"