[package]
name = "noahrepublic/components"
description = "Component system for binding constructors to entities. https://github.com/noahrepublic/RbxModules"
version = "0.1.4"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

