[package]
name = "noahrepublic/components"
description = "Component system for binding constructors to entities"
version = "0.1.2"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

