[package]
name = "noahrepublic/loader"
description = "A simple module load & store system"
version = "0.1.1"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

