[package]
name = "noahrepublic/loader"
description = "A simple module load & store system. https://github.com/noahrepublic/RbxModules"
version = "0.2.1"
license = "MIT"
authors = ["noahrepublic (https://github.com/noahrepublic)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

